export const shifts = [
  {
    id: 1,
    name: "Medics Teaching Hospital",
    location: "Z3, Ozumba Mbadiwe Ave, Eti-Osa, Lagos, Nigeria",
    payRate: "$50/hour",
    specialization: "General Practice",
    duration: "9am-5pm",
    jobDescription: "A full-time general practice shift.",
    date: "2024-09-15",
    skills: ["Pediatrics", "Emergency Medicine"],
  },
  {
    id: 2,
    name: "City Health Center",
    location: "123 Health Ave, Downtown, Lagos, Nigeria",
    payRate: "$40/hour",
    specialization: "Emergency",
    duration: "7am-3pm",
    jobDescription: "Emergency room shift.",
    date: "2024-09-16",
    skills: ["Emergency Care", "Pediatrics"],
  },
  {
    id: 3,
    name: "CarePlus Clinic",
    location: "456 Care St, Victoria Island, Lagos, Nigeria",
    payRate: "$45/hour",
    specialization: "Pediatrics",
    duration: "8am-4pm",
    jobDescription: "Pediatric shift.",
    date: "2024-09-17",
    skills: ["Pediatrics"],
  },
  // Additional shifts
  {
    id: 4,
    name: "Lagos City Hospital",
    location: "789 Main Street, Lagos Island, Lagos, Nigeria",
    payRate: "$55/hour",
    specialization: "Cardiology",
    duration: "10am-6pm",
    jobDescription: "Cardiology specialist shift.",
    date: "2024-09-18",
    skills: ["Cardiology", "Internal Medicine"],
  },
  {
    id: 5,
    name: "New Life Clinic",
    location: "321 Hope Ave, Lekki, Lagos, Nigeria",
    payRate: "$60/hour",
    specialization: "Obstetrics",
    duration: "8am-4pm",
    jobDescription: "Obstetrics shift.",
    date: "2024-09-19",
    skills: ["Obstetrics", "Gynecology"],
  },
  {
    id: 6,
    name: "Sunrise Medical Center",
    location: "654 Sun Street, Surulere, Lagos, Nigeria",
    payRate: "$48/hour",
    specialization: "Orthopedics",
    duration: "9am-5pm",
    jobDescription: "Orthopedics shift.",
    date: "2024-09-20",
    skills: ["Orthopedics", "Surgery"],
  },
  {
    id: 7,
    name: "Greenfield Hospital",
    location: "987 Greenfield Rd, Ikeja, Lagos, Nigeria",
    payRate: "$52/hour",
    specialization: "Neurology",
    duration: "10am-6pm",
    jobDescription: "Neurology specialist shift.",
    date: "2024-09-21",
    skills: ["Neurology", "Emergency Care"],
  },
  {
    id: 8,
    name: "Bright Future Clinic",
    location: "123 Bright St, Yaba, Lagos, Nigeria",
    payRate: "$47/hour",
    specialization: "Gastroenterology",
    duration: "8am-4pm",
    jobDescription: "Gastroenterology shift.",
    date: "2024-09-22",
    skills: ["Gastroenterology", "Internal Medicine"],
  },
  {
    id: 9,
    name: "Prime Health Center",
    location: "456 Prime Ave, Apapa, Lagos, Nigeria",
    payRate: "$50/hour",
    specialization: "Urology",
    duration: "7am-3pm",
    jobDescription: "Urology specialist shift.",
    date: "2024-09-23",
    skills: ["Urology", "Surgery"],
  },
  {
    id: 10,
    name: "West End Clinic",
    location: "789 West End Rd, Victoria Island, Lagos, Nigeria",
    payRate: "$49/hour",
    specialization: "Pulmonology",
    duration: "9am-5pm",
    jobDescription: "Pulmonology shift.",
    date: "2024-09-24",
    skills: ["Pulmonology", "Emergency Care"],
  },
  {
    id: 11,
    name: "Elite Medical Center",
    location: "321 Elite Blvd, Lekki, Lagos, Nigeria",
    payRate: "$53/hour",
    specialization: "Dermatology",
    duration: "8am-4pm",
    jobDescription: "Dermatology shift.",
    date: "2024-09-25",
    skills: ["Dermatology", "Internal Medicine"],
  },
  {
    id: 12,
    name: "Health Plus Clinic",
    location: "654 Health St, Surulere, Lagos, Nigeria",
    payRate: "$57/hour",
    specialization: "Endocrinology",
    duration: "10am-6pm",
    jobDescription: "Endocrinology shift.",
    date: "2024-09-26",
    skills: ["Endocrinology", "Internal Medicine"],
  },
  {
    id: 13,
    name: "Care Zone Hospital",
    location: "987 Care Rd, Ikeja, Lagos, Nigeria",
    payRate: "$50/hour",
    specialization: "Rheumatology",
    duration: "9am-5pm",
    jobDescription: "Rheumatology shift.",
    date: "2024-09-27",
    skills: ["Rheumatology", "Internal Medicine"],
  },
  {
    id: 14,
    name: "City View Medical Center",
    location: "123 City View Ave, Yaba, Lagos, Nigeria",
    payRate: "$55/hour",
    specialization: "Hematology",
    duration: "8am-4pm",
    jobDescription: "Hematology shift.",
    date: "2024-09-28",
    skills: ["Hematology", "Internal Medicine"],
  },
  {
    id: 15,
    name: "Bright Days Clinic",
    location: "456 Bright Days Rd, Apapa, Lagos, Nigeria",
    payRate: "$52/hour",
    specialization: "Nephrology",
    duration: "7am-3pm",
    jobDescription: "Nephrology specialist shift.",
    date: "2024-09-29",
    skills: ["Nephrology", "Emergency Care"],
  },
  {
    id: 16,
    name: "Health First Hospital",
    location: "789 Health First St, Victoria Island, Lagos, Nigeria",
    payRate: "$54/hour",
    specialization: "Oncology",
    duration: "9am-5pm",
    jobDescription: "Oncology shift.",
    date: "2024-09-30",
    skills: ["Oncology", "Emergency Care"],
  },
  {
    id: 17,
    name: "Safe Haven Clinic",
    location: "321 Safe Haven Blvd, Lekki, Lagos, Nigeria",
    payRate: "$58/hour",
    specialization: "Pediatric Surgery",
    duration: "8am-4pm",
    jobDescription: "Pediatric surgery shift.",
    date: "2024-10-01",
    skills: ["Pediatric Surgery", "Emergency Care"],
  },
  {
    id: 18,
    name: "MedCare Medical Center",
    location: "654 MedCare St, Surulere, Lagos, Nigeria",
    payRate: "$51/hour",
    specialization: "Geriatrics",
    duration: "10am-6pm",
    jobDescription: "Geriatrics shift.",
    date: "2024-10-02",
    skills: ["Geriatrics", "Internal Medicine"],
  },
  {
    id: 19,
    name: "Care Plus Hospital",
    location: "987 Care Plus Rd, Ikeja, Lagos, Nigeria",
    payRate: "$46/hour",
    specialization: "Family Medicine",
    duration: "9am-5pm",
    jobDescription: "Family medicine shift.",
    date: "2024-10-03",
    skills: ["Family Medicine", "Emergency Care"],
  },
  {
    id: 20,
    name: "Health Link Clinic",
    location: "123 Health Link Ave, Yaba, Lagos, Nigeria",
    payRate: "$59/hour",
    specialization: "Sports Medicine",
    duration: "8am-4pm",
    jobDescription: "Sports medicine shift.",
    date: "2024-10-04",
    skills: ["Sports Medicine", "Emergency Care"],
  },
  {
    id: 21,
    name: "Total Health Center",
    location: "456 Total Health St, Apapa, Lagos, Nigeria",
    payRate: "$60/hour",
    specialization: "Traumatology",
    duration: "7am-3pm",
    jobDescription: "Traumatology specialist shift.",
    date: "2024-10-05",
    skills: ["Traumatology", "Surgery"],
  },
  {
    id: 22,
    name: "Advanced Health Clinic",
    location: "789 Advanced Rd, Victoria Island, Lagos, Nigeria",
    payRate: "$62/hour",
    specialization: "Plastic Surgery",
    duration: "9am-5pm",
    jobDescription: "Plastic surgery shift.",
    date: "2024-10-06",
    skills: ["Plastic Surgery", "Emergency Care"],
  },
  {
    id: 23,
    name: "Lagos East Hospital",
    location: "321 Lagos East St, Lekki, Lagos, Nigeria",
    payRate: "$55/hour",
    specialization: "Cardiac Surgery",
    duration: "8am-4pm",
    jobDescription: "Cardiac surgery shift.",
    date: "2024-10-07",
    skills: ["Cardiac Surgery", "Emergency Care"],
  },
  {
    id: 24,
    name: "City Health Clinic",
    location: "654 City Health Blvd, Surulere, Lagos, Nigeria",
    payRate: "$57/hour",
    specialization: "Vascular Surgery",
    duration: "10am-6pm",
    jobDescription: "Vascular surgery shift.",
    date: "2024-10-08",
    skills: ["Vascular Surgery", "Emergency Care"],
  },
  {
    id: 25,
    name: "Future Health Center",
    location: "987 Future Rd, Ikeja, Lagos, Nigeria",
    payRate: "$50/hour",
    specialization: "Endocrine Surgery",
    duration: "9am-5pm",
    jobDescription: "Endocrine surgery shift.",
    date: "2024-10-09",
    skills: ["Endocrine Surgery", "Emergency Care"],
  },
  {
    id: 26,
    name: "Lagos Medical Center",
    location: "123 Lagos Med St, Yaba, Lagos, Nigeria",
    payRate: "$52/hour",
    specialization: "Urological Surgery",
    duration: "8am-4pm",
    jobDescription: "Urological surgery shift.",
    date: "2024-10-10",
    skills: ["Urological Surgery", "Emergency Care"],
  },
  {
    id: 27,
    name: "Bright Future Hospital",
    location: "456 Bright Future Rd, Apapa, Lagos, Nigeria",
    payRate: "$54/hour",
    specialization: "Neuro Surgery",
    duration: "7am-3pm",
    jobDescription: "Neuro surgery shift.",
    date: "2024-10-11",
    skills: ["Neuro Surgery", "Emergency Care"],
  },
  {
    id: 28,
    name: "City View Medical Center",
    location: "789 City View Ave, Victoria Island, Lagos, Nigeria",
    payRate: "$56/hour",
    specialization: "Gastrointestinal Surgery",
    duration: "9am-5pm",
    jobDescription: "Gastrointestinal surgery shift.",
    date: "2024-10-12",
    skills: ["Gastrointestinal Surgery", "Emergency Care"],
  },
  {
    id: 29,
    name: "Safe Haven Medical Center",
    location: "321 Safe Haven Blvd, Lekki, Lagos, Nigeria",
    payRate: "$58/hour",
    specialization: "Reconstructive Surgery",
    duration: "8am-4pm",
    jobDescription: "Reconstructive surgery shift.",
    date: "2024-10-13",
    skills: ["Reconstructive Surgery", "Emergency Care"],
  },
  {
    id: 30,
    name: "Health Zone Clinic",
    location: "654 Health Zone St, Surulere, Lagos, Nigeria",
    payRate: "$60/hour",
    specialization: "Thoracic Surgery",
    duration: "10am-6pm",
    jobDescription: "Thoracic surgery shift.",
    date: "2024-10-14",
    skills: ["Thoracic Surgery", "Emergency Care"],
  },
  {
    id: 31,
    name: "Prime Medical Center",
    location: "987 Prime Rd, Ikeja, Lagos, Nigeria",
    payRate: "$62/hour",
    specialization: "Pediatric Surgery",
    duration: "9am-5pm",
    jobDescription: "Pediatric surgery shift.",
    date: "2024-10-15",
    skills: ["Pediatric Surgery", "Emergency Care"],
  },
  {
    id: 32,
    name: "Elite Health Center",
    location: "123 Elite Blvd, Yaba, Lagos, Nigeria",
    payRate: "$55/hour",
    specialization: "Nephrology",
    duration: "8am-4pm",
    jobDescription: "Nephrology shift.",
    date: "2024-10-16",
    skills: ["Nephrology", "Emergency Care"],
  },
  {
    id: 33,
    name: "Health First Clinic",
    location: "456 Health First Ave, Apapa, Lagos, Nigeria",
    payRate: "$57/hour",
    specialization: "Cardiology",
    duration: "7am-3pm",
    jobDescription: "Cardiology shift.",
    date: "2024-10-17",
    skills: ["Cardiology", "Emergency Care"],
  },
  {
    id: 34,
    name: "Care Zone Clinic",
    location: "789 Care Zone Rd, Victoria Island, Lagos, Nigeria",
    payRate: "$59/hour",
    specialization: "Dermatology",
    duration: "9am-5pm",
    jobDescription: "Dermatology shift.",
    date: "2024-10-18",
    skills: ["Dermatology", "Emergency Care"],
  },
  {
    id: 35,
    name: "Total Health Clinic",
    location: "321 Total Health St, Lekki, Lagos, Nigeria",
    payRate: "$61/hour",
    specialization: "Orthopedics",
    duration: "8am-4pm",
    jobDescription: "Orthopedics shift.",
    date: "2024-10-19",
    skills: ["Orthopedics", "Emergency Care"],
  },
  {
    id: 36,
    name: "Advanced Health Center",
    location: "654 Advanced Health Rd, Surulere, Lagos, Nigeria",
    payRate: "$63/hour",
    specialization: "Hematology",
    duration: "10am-6pm",
    jobDescription: "Hematology shift.",
    date: "2024-10-20",
    skills: ["Hematology", "Emergency Care"],
  },
  {
    id: 37,
    name: "City View Hospital",
    location: "987 City View Ave, Ikeja, Lagos, Nigeria",
    payRate: "$65/hour",
    specialization: "Neuro Surgery",
    duration: "9am-5pm",
    jobDescription: "Neuro surgery shift.",
    date: "2024-10-21",
    skills: ["Neuro Surgery", "Emergency Care"],
  },
  {
    id: 38,
    name: "Bright Future Medical Center",
    location: "123 Bright Future Blvd, Yaba, Lagos, Nigeria",
    payRate: "$67/hour",
    specialization: "Plastic Surgery",
    duration: "8am-4pm",
    jobDescription: "Plastic surgery shift.",
    date: "2024-10-22",
    skills: ["Plastic Surgery", "Emergency Care"],
  },
  {
    id: 39,
    name: "Health Zone Medical Center",
    location: "456 Health Zone Ave, Apapa, Lagos, Nigeria",
    payRate: "$68/hour",
    specialization: "Traumatology",
    duration: "7am-3pm",
    jobDescription: "Traumatology shift.",
    date: "2024-10-23",
    skills: ["Traumatology", "Emergency Care"],
  },
  {
    id: 40,
    name: "Lagos South Clinic",
    location: "789 Lagos South St, Victoria Island, Lagos, Nigeria",
    payRate: "$70/hour",
    specialization: "Gastroenterology",
    duration: "9am-5pm",
    jobDescription: "Gastroenterology shift.",
    date: "2024-10-24",
    skills: ["Gastroenterology", "Emergency Care"],
  },
  {
    id: 41,
    name: "MedPlus Hospital",
    location: "321 MedPlus Rd, Lekki, Lagos, Nigeria",
    payRate: "$72/hour",
    specialization: "Obstetrics",
    duration: "8am-4pm",
    jobDescription: "Obstetrics shift.",
    date: "2024-10-25",
    skills: ["Obstetrics", "Emergency Care"],
  },
  {
    id: 42,
    name: "Safe Haven Hospital",
    location: "654 Safe Haven Blvd, Surulere, Lagos, Nigeria",
    payRate: "$74/hour",
    specialization: "Rheumatology",
    duration: "10am-6pm",
    jobDescription: "Rheumatology shift.",
    date: "2024-10-26",
    skills: ["Rheumatology", "Emergency Care"],
  },
  {
    id: 43,
    name: "Bright Future Clinic",
    location: "987 Bright Future Ave, Ikeja, Lagos, Nigeria",
    payRate: "$76/hour",
    specialization: "Endocrinology",
    duration: "9am-5pm",
    jobDescription: "Endocrinology shift.",
    date: "2024-10-27",
    skills: ["Endocrinology", "Emergency Care"],
  },
  {
    id: 44,
    name: "Health First Center",
    location: "123 Health First Rd, Yaba, Lagos, Nigeria",
    payRate: "$78/hour",
    specialization: "Oncology",
    duration: "8am-4pm",
    jobDescription: "Oncology shift.",
    date: "2024-10-28",
    skills: ["Oncology", "Emergency Care"],
  },
  {
    id: 45,
    name: "Total Health Medical Center",
    location: "456 Total Health Ave, Apapa, Lagos, Nigeria",
    payRate: "$80/hour",
    specialization: "Geriatrics",
    duration: "7am-3pm",
    jobDescription: "Geriatrics shift.",
    date: "2024-10-29",
    skills: ["Geriatrics", "Emergency Care"],
  },
  {
    id: 46,
    name: "Future Health Hospital",
    location: "789 Future Health Rd, Victoria Island, Lagos, Nigeria",
    payRate: "$82/hour",
    specialization: "Pulmonology",
    duration: "9am-5pm",
    jobDescription: "Pulmonology shift.",
    date: "2024-10-30",
    skills: ["Pulmonology", "Emergency Care"],
  },
  {
    id: 47,
    name: "Lagos North Clinic",
    location: "321 Lagos North Blvd, Lekki, Lagos, Nigeria",
    payRate: "$84/hour",
    specialization: "Neurointervention",
    duration: "8am-4pm",
    jobDescription: "Neurointervention shift.",
    date: "2024-10-31",
    skills: ["Neurointervention", "Emergency Care"],
  },
  {
    id: 48,
    name: "City Health Medical Center",
    location: "654 City Health St, Surulere, Lagos, Nigeria",
    payRate: "$86/hour",
    specialization: "Reproductive Endocrinology",
    duration: "10am-6pm",
    jobDescription: "Reproductive endocrinology shift.",
    date: "2024-11-01",
    skills: ["Reproductive Endocrinology", "Emergency Care"],
  },
  {
    id: 49,
    name: "Prime Medical Clinic",
    location: "987 Prime Blvd, Ikeja, Lagos, Nigeria",
    payRate: "$88/hour",
    specialization: "Orthopedic Surgery",
    duration: "9am-5pm",
    jobDescription: "Orthopedic surgery shift.",
    date: "2024-11-02",
    skills: ["Orthopedic Surgery", "Emergency Care"],
  },
  {
    id: 50,
    name: "Elite Health Medical Center",
    location: "123 Elite Health Rd, Yaba, Lagos, Nigeria",
    payRate: "$90/hour",
    specialization: "Neuro-Oncology",
    duration: "8am-4pm",
    jobDescription: "Neuro-oncology shift.",
    date: "2024-11-03",
    skills: ["Neuro-Oncology", "Emergency Care"],
  },
];
